### PR TITLE
Update to python3 and switch to requests

### PR DESCRIPTION
**Pull request by jennyfothergill**
Hi there!
I think your code is awesome and would like to use it in an [interactive diffractometer](https://github.com/jennyfothergill/diffract) I'm working on. (I'd like to use it to encode the rotation matrix in the image and so on.) Anyway, I took the time to update ImageStore to python3, so I thought I'd share it with you. :) I used [black](https://black.readthedocs.io/en/stable/), [2to3](https://docs.python.org/2/library/2to3.html), and [isort](https://github.com/timothycrosley/isort) for much of this update. I also switched urllib2 to [requests](https://requests.readthedocs.io/en/master/) because it's just a great library. Please also let me know how your code is licensed or how you'd like to be acknowledged for your hard work if I use it in a publication. 
Thank you,
Jenny

### CODE REVIEW

**Comment by huntfx** [comment]
Hey, it's really awesome you found this useful (especially when there's no documentation), thanks for sharing the updates :)  I'm away from my PC over xmas so I'll give it a try once I'm back. This code is 3 years old though, so since I've improved a lot, I'm very tempted to start over with a fresh improved version.

As to license, depending on how strict things are when writing papers, technically this doesn't have one yet, but I'd class it as MIT (will add the file if I rewrite it). I guess my name would be cool if you did an acknowledgement, I don't really know the standard for doing them though :)

**Comment by jennyfothergill** [comment]
Awesome! I was away as well, so no worries.
OK, I will make sure to acknowledge you! (I don't really know the standard either, but if there's any info you'd like in it just let me know.)
I'm also interested in updating the code to use RGBA images, so I'll share that with you if/when I get around to it. :)

**Comment by huntfx** [comment]
Ah alright cool, that's a good idea. As a warning though, I have a feeling the 3 channels may be a bit too hardcoded currently, so it may be easier for me to make a v2 instead of you trying to add in the functionality (then I could add audio support too if it's feasible in python).

I do definitely want to do it sometime soon, the code is just a bit more complicated than I remember and I'm off on holiday in a few days, so it won't be right away haha :)

I like the idea of designing it similar to how logging has its handlers, so it would have the default ones, but it'd be easy to create a custom one for your own filetype.

**Comment by huntfx** [comment]
I've made a start on a [new version](https://github.com/Peter92/ImageStore/blob/rewrite/pyhide.py) that's a ton faster. It has support for `L`, `RGB` and `RGBA` but only lightly tested. I'll get your code merged in for now anyway and keep mine in a branch until I know it's working properly :)

Edit: Finished it now and put it up on [pypi](https://pypi.org/project/pyhide) :)

**Pull request merged**
